// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwhkoilnqtoiybkacyhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aGtvaWxucXRvaXlia2FjeWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjkzNDQsImV4cCI6MjA2MzI0NTM0NH0.CM4rEPPGibWJuMW-297KPgLyzCd4U28V_uEXITrs0-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);